### ISSUE TITLE
Contao Leads

### ISSUE THREAD

**Issue by 9teufel** [netzmacht/contao-subforms#4]
Contao Leads ist ja sehr häufig im Einsatz, leider werden keine Formulardaten von Subforms gespeichert.

"In Anfrage sichern" lässt sich aktivieren, jedoch zeigt das keine Wirkung...

**Comment by dmolineus** [comment]
Dann hat sich zwischenzeitlich Contao Leads geändert. Es war eigentlich dafür konzipiert.

**Comment by dmolineus** [comment]
Did you follow the steps in the readme:

1. Define a master form containing all fields
2. Configure the subform mapping in the subform fields?

**Comment by 9teufel** [comment]
Ja es ist genau so konfiguriert.

Habe eben auch den Mail-Versand getestet. 
Hier werden die Felder vom Subformular nicht übertragen.

Getestet mit "Per E-Mail versenden" (Datenformat Rohdaten) und auch über das Notification Center.

Contao 4.4.20

**Comment by dmolineus** [comment]
Die Erweiterung steht ja derzeit gar nicht für Contao 4 zur Verfügung, es muss sich also eh um eine irgendwie gepatchte Version handeln für die ich hier keine Fehleranalyse betreiben kann. Sollte der Fehler unter Contao 3 auch bestehen und eine reproduzierbare Konfiguration vorliegen, lasse ich das Ticket offen.

**Comment by 9teufel** [comment]
Sorry für die Verwirrung, du kannst das Ticket wohl schließen...

Hatte gedacht ich habe deine Erweiterung installiert, es war jedoch
https://github.com/m-vo/contao-nested-forms

**Comment by dmolineus** [comment]
Wusste gar nicht, dass es da ein anderes Paket gibt. Gut zu wissen, da kann ich mir die Migration zu Contao 4 ggf. sparen, falls der Leadssupport dort nachgerüstet wird.
